//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicCrud_Serrano_Brian
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employeeInfo
    {
        public int Id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public int age { get; set; }
        public System.DateTime birthday { get; set; }
        public string contact_number { get; set; }
        public string address { get; set; }
    }
}
